### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by pradal**
@RamiALBASHA : Can I merge the branch?

### CODE REVIEW

**Comment by RamiALBASHA** [comment]
> 
> 
> @RamiALBASHA : Can I merge the branch?

Yes, but please check first whether you can generate the doc and that all files are properly used.

**Comment by pradal** [comment]
I will do taht directly on readthedoc.

**Comment by RamiALBASHA** [comment]
checkout index_new.rst. This is the one that should be used.

**Comment by RamiALBASHA** [comment]
I've just Seen the Doc. Are you sure it's properly merged? I don't see thé ecophsio description for instance..

**Comment by pradal** [comment]
I hope so. Look at it and gave me feedback.

**Comment by RamiALBASHA** [comment]
The rst files are in master Doc but the doc sors not incluse them : https://hydroshoot.readthedocs.io/
Have you replaced index.rst by index_new.rst ?

**Comment by pradal** [comment]
Have you refresh your browser (ctrl+R)?

**Comment by RamiALBASHA** [comment]
Lol ! That's ok !

**Pull request merged**
